path: ./
jobs: 10
extensions:
  - php
exclude:
  - cavalcade/vendor

  - vendor
  - wordpress

  - wp-content/platform

  - wp-content/plugins/rewrite-rules-inspector

  - wp-content/themes/twentyseventeen
