sudo: required

language: php
php:
  - '7.1'

services:
  - docker

stages:
  - test
  - deploy

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";

jobs:
  include:

    - stage: test
      env:
        - TEST=phpcs
      before_script:
        - cd ./app
        - composer install
      script:
        - composer analyse:phpcs


    - stage: test
      env:
        - TEST=phplint
      before_script:
        - cd ./app
        - composer install
      script:
        - composer analyse:phplint


    - stage: deploy
      before_script:
        - make pull

      script:
        - make build

        - if [ "$TRAVIS_BRANCH" == "master" ]; then
            make travis-deploy;
          fi

notifications:
  webhooks:
    - https://h2a-hubot.herokuapp.com/webhooks/travis
