sudo: required

language: php
php:
  - '7.1'

services:
  - docker

stages:
  - analyse
  - build-app
  - build-services

install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";

jobs:
  include:

    - stage: analyse
      env:
        - TEST=phpcs
      before_script:
        - composer install
      script:
        - composer analyse:phpcs


    - stage: analyse
      env:
        - TEST=phplint
      before_script:
        - composer install
      script:
        - composer analyse:phplint

    - stage: build-app
      before_script:
        - make travis-app-before_script
      script:
        - make travis-app-script
      after_success:
        - make travis-app-after_success

    - stage: build-services
      before_script:
        - make travis-nginx-before_script
      script:
        - make travis-nginx-script
      after_success:
        - make travis-nginx-after_success

    - stage: build-services
      env:
        - SERVICE=php
      before_script:
        - make travis-php-before_script
      script:
        - make travis-php-script
      after_success:
        - make travis-php-after_success

    - stage: build-services
      env:
        - SERVICE=php-dev
      before_script:
        - make travis-php-dev-before_script
      script:
        - make travis-php-dev-script
      after_success:
        - make travis-php-dev-after_success

    - stage: build-services
      env:
        - SERVICE=queue
      before_script:
        - make travis-queue-before_script
      script:
        - make travis-queue-script
      after_success:
        - make travis-queue-after_success



notifications:
  webhooks:
    - https://h2a-hubot.herokuapp.com/webhooks/travis
