sudo: required

services:
  - docker

before_install:
  - make pull

script:
  - make build

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      make travis-deploy;
    fi
