version: "3"

services:
  dev-services:
    image: howtoadhd/dev-services
    restart: always
    volumes:
      - ./data:/data
    ports:
      - 80:80
      - 443:443
      - 3306:3306
      - 11212:11212
    networks:
      default:
        aliases:
          - aws.howtoadhd.pink
          - s3.aws.howtoadhd.pink
          - ses.aws.howtoadhd.pink
          - mock.s3.aws.howtoadhd.pink

  queue:
    image: builder:queue-dev
    restart: always
    depends_on:
      - dev-services
    volumes:
      - ..:/app:ro
    extra_hosts:
      - howtoadhd.pink:172.18.0.1
    env_file:
      - config.env
    environment:
      WP_DEBUG: "false"

  php:
    image: builder:php-dev
    restart: always
    depends_on:
      - dev-services
    volumes:
      - ..:/app:ro
    extra_hosts:
      - howtoadhd.pink:172.18.0.1
    env_file:
      - config.env
    environment:
      WP_DEBUG: "false"
      XDEBUG_CONFIG: "remote_host=192.168.0.45"
      PHP_IDE_CONFIG: "serverName=howtoadhd"

  nginx:
    image: builder:nginx
    restart: always
    depends_on:
      - php
    volumes:
      - ..:/app:ro
    environment:
      FASTCGI_PASS: php:9000
      ROOT_DOMAIN:  howtoadhd.pink
